[package]
name = "rusty-os"
version = "0.1.0"
authors = ["Valentin Tunev <hdbuster@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"